apiVersion: v1
kind: Namespace
metadata:
  name: quran-app

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: quran-app
type: Opaque
stringData:
  DB_HOST: "192.168.8.70"
  DB_PORT: "5432"
  DB_NAME: "quran"
  DB_USER: "quran"
  DB_PASSWORD: "quran"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quran-backend
  namespace: quran-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quran-backend
  template:
    metadata:
      labels:
        app: quran-backend
    spec:
      containers:
        - name: backend
          image: 192.168.8.25:5000/quran-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: backend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: quran-backend-service
  namespace: quran-app
spec:
  selector:
    app: quran-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 33333
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quran-app-ingress
  namespace: quran-app
spec:
  ingressClassName: nginx
  rules:
    - host: quran-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quran-backend-service
                port:
                  number: 8000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quran-backend-hpa
  namespace: quran-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quran-backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50