[app]
APP_ENV = development
CORS_ORIGINS = *

[database]
DB_TYPE = docker
DB_HOST = db
DB_PORT = 5432
DB_USER = quran
DB_PASSWORD = quran
DB_NAME = quran

[security]
JWT_SECRET_KEY = dev_secret_key
ALTCHA_HMAC_KEY = dev_secret_key

[embedding]
EMBEDDING_THREADS = 6

[admin]
ADMIN_EMAIL = admin@quran.app
ADMIN_PASSWORD = changeme
